language: python
cache: pip
dist: bionic
sudo: false
python:
  - "3.6"
  - "3.7"
install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.23.0/geckodriver-v0.23.0-linux64.tar.gz
  - tar -xvzf geckodriver*
  - chmod +x geckodriver
  - sudo ln -s `pwd`/geckodriver /usr/bin/geckodriver
  - pip install .
  - pip install selenium coverage
script:
  - coverage run manage.py test
after_success:
  - pip install codecov
  - codecov
notifications:
    email: false
