# Generated by Django 2.1.2 on 2018-10-21 14:26

from django.db import migrations, models
import kindeditor.fields


class Migration(migrations.Migration):

    dependencies = [("demo_app", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80)),
                ("content", kindeditor.fields.RichTextField()),
            ],
        )
    ]
