# Generated by Django 2.1.2 on 2018-11-29 18:12

from django.db import migrations, models
import django.utils.timezone
import kindeditor.fields


class Migration(migrations.Migration):

    dependencies = [("demo_app", "0002_article")]

    operations = [
        migrations.DeleteModel(name="ExampleModel"),
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "article",
                "verbose_name_plural": "article",
            },
        ),
        migrations.AddField(
            model_name="article",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="article",
            name="content",
            field=kindeditor.fields.RichTextField(verbose_name="content"),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=80, verbose_name="title"),
        ),
    ]
