# Generated by Django 2.1.3 on 2018-11-29 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("demo_app", "0003_auto_20181130_0212")]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "article",
                "verbose_name_plural": "articles",
            },
        )
    ]
