__title__ = "django-kindeditor"
__description__ = "Django admin KindEditor integration."
__url__ = "https://github.com/waketzheng/django-kindeditor"
__version__ = "0.3.0"
__author__ = "Waket Zheng"
__author_email__ = "waketzheng@gmail.com"
__license__ = "MIT"
__copyright__ = "Copyright 2019 Waket Zheng"
